name: GitLab flow action for tenant bootstrap repositories
description: Action for provisioning and destroying clusters, updating and synchronizing releases, and managing project dependencies.

inputs:
  github_token_repo_full_access:
    description: GitHub token with full access permissions to repositories (used by installer script and RMK).
    required: true
  allowed_environments:
    description: Allowed environments participating in releases for RMK commands "destroy", "helmfile_validate", "project_update", "provision", "release_sync", "release_update".
    required: true
    default: develop,staging
  cluster_provider_credentials:
    description: |
      Credentials in JSON format for different environments and cluster providers.
      Example:
      cluster_provider_credentials: |
        {
            "develop": {
                "cluster_providers": {
                    "aws": {
                        "AWS_ACCESS_KEY_ID": "<aws_access_key_id>",
                        "AWS_SECRET_ACCESS_KEY": "<aws_secret_access_key>",
                        "AWS_REGION": "us-east-1"
                    },
                    "azure": {
                        "AZURE_CLIENT_ID": "<azure_client_id>",
                        "AZURE_CLIENT_SECRET": "<azure_client_secret>",
                        "AZURE_LOCATION": "eastus",
                        "AZURE_SUBSCRIPTION_ID": "<azure_subscription_id>",
                        "AZURE_TENANT_ID": "<azure_tenant_id>"
                    },
                    "gcp": {
                        "GOOGLE_APPLICATION_CREDENTIALS": {
                            "type": "service_account",
                            "project_id": "<google_project_id>",
                            "private_key_id": "<google_private_key_id>",
                            "private_key": "-----BEGIN PRIVATE KEY-----<example_cert>-----END PRIVATE KEY-----",
                            "client_email": "example@example.iam.gserviceaccount.com",
                            "client_id": "<google_client_id>",
                            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                            "token_uri": "https://oauth2.googleapis.com/token",
                            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/example%40example.iam.gserviceaccount.com",
                            "universe_domain": "googleapis.com"
                        },
                        "GCP_REGION": "us-east1"
                    }
                }
            },
            "production": {
                "cluster_providers": {
                    "aws": {
                        "AWS_ACCESS_KEY_ID": "<aws_access_key_id>",
                        "AWS_SECRET_ACCESS_KEY": "<aws_secret_access_key>",
                        "AWS_REGION": "us-east-1"
                    },
                    "azure": {
                        "AZURE_CLIENT_ID": "<azure_client_id>",
                        "AZURE_CLIENT_SECRET": "<azure_client_secret>",
                        "AZURE_LOCATION": "eastus",
                        "AZURE_SUBSCRIPTION_ID": "<azure_subscription_id>",
                        "AZURE_TENANT_ID": "<azure_tenant_id>"
                    },
                    "gcp": {
                        "GOOGLE_APPLICATION_CREDENTIALS": {
                            "type": "service_account",
                            "project_id": "<google_project_id>",
                            "private_key_id": "<google_private_key_id>",
                            "private_key": "-----BEGIN PRIVATE KEY-----<example_cert>-----END PRIVATE KEY-----",
                            "client_email": "example@example.iam.gserviceaccount.com",
                            "client_id": "<google_client_id>",
                            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                            "token_uri": "https://oauth2.googleapis.com/token",
                            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/example%40example.iam.gserviceaccount.com",
                            "universe_domain": "googleapis.com"
                        },
                        "GCP_REGION": "us-east1"
                    }
                }
            },
            "staging": {
                "cluster_providers": {
                    "aws": {
                        "AWS_ACCESS_KEY_ID": "<aws_access_key_id>",
                        "AWS_SECRET_ACCESS_KEY": "<aws_secret_access_key>",
                        "AWS_REGION": "us-east-1"
                    },
                    "azure": {
                        "AZURE_CLIENT_ID": "<azure_client_id>",
                        "AZURE_CLIENT_SECRET": "<azure_client_secret>",
                        "AZURE_LOCATION": "eastus",
                        "AZURE_SUBSCRIPTION_ID": "<azure_subscription_id>",
                        "AZURE_TENANT_ID": "<azure_tenant_id>"
                    },
                    "gcp": {
                        "GOOGLE_APPLICATION_CREDENTIALS": {
                            "type": "service_account",
                            "project_id": "<google_project_id>",
                            "private_key_id": "<google_private_key_id>",
                            "private_key": "-----BEGIN PRIVATE KEY-----<example_cert>-----END PRIVATE KEY-----",
                            "client_email": "example@example.iam.gserviceaccount.com",
                            "client_id": "<google_client_id>",
                            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                            "token_uri": "https://oauth2.googleapis.com/token",
                            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/example%40example.iam.gserviceaccount.com",
                            "universe_domain": "googleapis.com"
                        },
                        "GCP_REGION": "us-east1"
                    }
                }
            }
        }
    required: true
  rmk_cluster_provider:
    description: Cluster provider. Allowed values are "aws", "azure", "gcp".
    required: true
    default: aws
  rmk_version:
    description: RMK version.
    required: false
    default: latest
  rmk_download_url:
    description: |
      URL of the download script for RMK installation.
      Example:
        rmk_download_url: https://edenlabllc-rmk.s3.eu-north-1.amazonaws.com/rmk/s3-installer
    required: false
    default: https://edenlabllc-rmk.s3.eu-north-1.amazonaws.com/rmk/s3-installer
  rmk_slack_notifications:
    description: Enable Slack notifications.
    required: false
    default: false
  rmk_slack_webhook:
    description: URL for Slack webhook (required if rmk_slack_notifications=true).
    required: false
    default: ""
  rmk_slack_channel:
    description: Channel name for Slack notification (required if rmk_slack_notifications=true).
    required: false
    default: ""
  rmk_slack_message_details:
    description: |
      Additional information in the body of the Slack message (only if rmk_slack_notifications=true).
      Example:
      rmk_slack_message_details: |
        GitHub Actions Build URL: <github.server_url>/<github.repository>/actions/runs/<github.run_id>
        GitHub Actions Build Number: <github.run_number>
    required: false
    default: ""
  rmk_command:
    description: Command to run CD in RMK. Allowed values are "destroy", "helmfile_validate", "project_update", "provision", "release_sync", "release_update".
    required: true
  rmk_update_skip_deploy:
    description: Whether to skip deploy and commit only when running release update in RMK (only if rmk_command=release_update).
    required: false
    default: false
  rmk_sync_labels:
    description: |
      List of labels when running sync in RMK (only if rmk_command=release_sync).
      Example:
      rmk_sync_labels: |
        scope=kodjin
        app=fhir-server-api
    required: false
    default: ""
  rmk_release_repository_full_name:
    description: Image repository full name of application (includes registry URL and repository_name, only if rmk_command=release_update).
    required: false
  rmk_release_version:
    description: Current application version (only if rmk_command=release_update).
    required: false
  rmk_project_dependency_name:
    description: Dependency name. Allows using a set of RMK commands to project dependency version update to project.yaml file (only if rmk_command=project_update).
    required: false
  rmk_project_dependency_version:
    description: Dependency version. Allows using a set of RMK commands to project dependency version update to project.yaml file (only if rmk_command=project_update).
    required: false
outputs:
  environment:
    description: Current CD environment.
  git_branch:
    description: Git branch.
  rmk_release_repository_full_name:
    description: Image repository full name of application (includes registry URL and repository_name).
  rmk_release_version:
    description: Current application version.
runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install python dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Execute main script
      id: main
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_GITHUB_TOKEN_REPO_FULL_ACCESS: ${{ inputs.github_token_repo_full_access }}
        INPUT_ALLOWED_ENVIRONMENTS: ${{ inputs.allowed_environments }}
        INPUT_CLUSTER_PROVIDER_CREDENTIALS: ${{ inputs.cluster_provider_credentials }}
        INPUT_RMK_CLUSTER_PROVIDER: ${{ inputs.rmk_cluster_provider }}
        INPUT_RMK_VERSION: ${{ inputs.rmk_version }}
        INPUT_RMK_DOWNLOAD_URL: ${{ inputs.rmk_download_url }}
        INPUT_RMK_SLACK_NOTIFICATIONS: ${{ inputs.rmk_slack_notifications }}
        INPUT_RMK_SLACK_WEBHOOK: ${{ inputs.rmk_slack_webhook }}
        INPUT_RMK_SLACK_CHANNEL: ${{ inputs.rmk_slack_channel }}
        INPUT_RMK_SLACK_MESSAGE_DETAILS: ${{ inputs.rmk_slack_message_details }}
        INPUT_RMK_COMMAND: ${{ inputs.rmk_command }}
        INPUT_RMK_UPDATE_SKIP_DEPLOY: ${{ inputs.rmk_update_skip_deploy }}
        INPUT_RMK_SYNC_LABELS: ${{ inputs.rmk_sync_labels }}
        INPUT_RMK_RELEASE_REPOSITORY_FULL_NAME: ${{ inputs.rmk_release_repository_full_name }}
        INPUT_RMK_RELEASE_VERSION: ${{ inputs.rmk_release_version }}
        INPUT_RMK_PROJECT_DEPENDENCY_NAME: ${{ inputs.rmk_project_dependency_name }}
        INPUT_RMK_PROJECT_DEPENDENCY_VERSION: ${{ inputs.rmk_project_dependency_version }}
