name: GitLab flow action for tenant bootstrap repositories
description: |
inputs:
  github_token_repo_full_access:
    description: GitHub token with full access permissions to repositories (used by installer script and rmk).
    required: true
  cloudflare_token:
    description: Cloudflare token for DNS provisioning (used by rmk).
    required: true
  cd_develop_aws_region:
    description: AWS region of the AWS account deploying applications to EKS for develop.
    required: true
  cd_develop_aws_access_key_id:
    description: AWS access key ID of the AWS account deploying applications to EKS for develop.
    required: true
  cd_develop_aws_secret_access_key:
    description: AWS secret access key of the AWS account deploying applications to EKS for develop.
    required: true
  cd_staging_aws_region:
    description: AWS region of the AWS account deploying applications to EKS for staging.
    required: false
  cd_staging_aws_access_key_id:
    description: AWS access key ID of the AWS account deploying applications to EKS for staging.
    required: false
  cd_staging_aws_secret_access_key:
    description: AWS secret access key of the AWS account deploying applications to EKS for staging.
    required: false
  allowed_environments:
    description: Allowed environments participating in releases for rmk commands update & sync.
    required: true
    default: develop,staging
  cluster_provisioner:
    description: Allows using a set of rmk commands to provision cluster according to the specification tenant repositories.
    required: true
    default: false
  reindexer_release_name:
    description: Reindexer release name
    required: false
    default: fhir-server-search-reindexer
  rmk_version:
    description: rmk version. Default value is "latest".
    required: false
    default: latest
  rmk_slack_notifications:
    description: Enable slack notifications.
    required: false
    default: false
  rmk_slack_webhook:
    description: Url for slack webhook (required if rmk_slack_notifications=true).
    required: false
    default: ""
  rmk_slack_channel:
    description: Channel name for slack notification (required if rmk_slack_notifications=true).
    required: false
    default: ""
  rmk_slack_message_details:
    description: |
      Additional information in the body of the slack message (only if rmk_slack_notifications=true).
      Example:
      rmk_slack_message_details: |
        GitHub Action Url: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
        Build Number: ${GITHUB_RUN_NUMBER}
    required: false
    default: ""
  rmk_command:
    description: Command to run CD in rmk. Allowed values are "update", "sync", "provision", "reindex", "destroy".
    required: false
  rmk_update_helmfile_repos_command:
    description: Helmfile command to update repos when running update in rmk. Allowed values are "" (do nothing), "repos", "fetch" (only if rmk_command=update).
    required: false
    default: ""
  rmk_update_skip_deploy:
    description: Whether to skip deploy and commit only when running update in rmk (only if rmk_command=update).
    required: false
    default: false
  rmk_sync_skip_deps:
    description: Whether to skip running "helm repo update" and "helm dependency build" when running sync in rmk (only if rmk_command=sync).
    required: false
    default: false
  rmk_sync_labels:
    description: |
      List of labels when running sync in rmk (only if rmk_command=sync).
      Example:
      rmk_sync_labels: |
        scope=kodjin
        app=fhir-server-api
    required: false
    default: ""
  repository_full_name:
    description: Image repository full name of application (includes registry URL and repository_name, only if rmk_command=update).
    required: false
  version:
    description: Current application version (only if rmk_command=update).
    required: false
  destroy_clusters:
    description: Destroy all clusters by feature/ffs-\d+ and release/rc-\d+ branch patterns (case-insensitive).
    required: false
    default: false
  check_orphaned_clusters:
    description: Whether to check for orphaned clusters (only if destroy_clusters=true).
    required: false
    default: true
  check_orphaned_volumes:
    description: Whether to check for orphaned volumes (only if destroy_clusters=true).
    required: false
    default: false
  mongodb_backup:
    description: Make new backup of MongoDB databases.
    required: false
    default: false
  mongodb_restore:
    description: Restore backup of MongoDB databases.
    required: false
    default: false
  routes_test:
    description: Execute routes test.
    required: false
    default: false
  routes_test_branch:
    description: Branch for fhir.routes.tests repository.
    required: false
    default: master
  reindexer_collections:
    description: Collections to reindex (if empty, then reindex all from values).
    required: false

outputs:
  git_branch:
    description: Git branch.
  repository_full_name:
    description: Image repository full name of application (includes registry URL and repository_name).
  version:
    description: Current application version.
  environment:
    description: Current CD environment.
runs:
  using: docker
  image: docker://core.gitlabflow.cd.action
