name: Validate Helmfile templates

on:
  pull_request:

env:
  # The cluster provider: azure, aws, gcp
  RMK_CLUSTER_PROVIDER: aws

jobs:
  helmfile-template-validate:
    name: Validate Helmfile templates
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run gitlabflow action
        uses: edenlab/gitlabflow.cd.action@v2
        with:
          cluster_provider_credentials: ${{ secrets.CLUSTER_PROVIDER_CREDENTIALS }}
          github_token_repo_full_access: ${{ secrets.GITHUB_TOKEN_REPO_FULL_ACCESS }}
          rmk_cluster_provider: ${{ env.RMK_CLUSTER_PROVIDER }}
          rmk_command: helmfile_validate
