name: Release sync GitLab CD workflow

on:
  push:
    branches:
      - develop
      - staging

concurrency:
  group: release-sync-${{ github.ref }}
  cancel-in-progress: false

env:
  # The cluster provider: azure, aws, gcp
  RMK_CLUSTER_PROVIDER: aws

jobs:
  release-sync:
    name: 'Sync releases for branch: ${{ github.ref_name }}.'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run gitlabflow action
        uses: edenlabllc/gitlabflow.cd.action@v2
        with:
          allowed_environments: develop,staging
          cluster_provider_credentials: ${{ secrets.CLUSTER_PROVIDER_CREDENTIALS }}
          github_token_repo_full_access: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          rmk_cluster_provider: ${{ env.RMK_CLUSTER_PROVIDER }}
          rmk_command: release_sync
          rmk_slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
