name: Release update GitLab CD workflow

on:
  workflow_dispatch:
    inputs:
      repository_full_name:
        description: Enter the image repository full name of application (includes registry URL and repository_name).
        required: true
      version:
        description: Enter current application version.
        required: true
      rmk_version:
        description: Specify RMK version.
        required: false
        default: latest

env:
  # The cluster provider: azure, aws, gcp
  RMK_CLUSTER_PROVIDER: aws

jobs:
  release-update:
    name: 'Update ${{ github.event.inputs.rmk_release_repository_full_name }} image to version ${{ github.event.inputs.rmk_release_version }} for branch: ${{ github.ref_name }}.'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Run gitlabflow action
        uses: edenlabllc/gitlabflow.cd.action@v2
        with:
          allowed_environments: develop
          cluster_provider_credentials: ${{ secrets.CLUSTER_PROVIDER_CREDENTIALS }}
          github_token_repo_full_access: ${{ secrets.GH_TOKEN_REPO_FULL_ACCESS }}
          rmk_cluster_provider: ${{ env.RMK_CLUSTER_PROVIDER }}
          rmk_command: release_update
          rmk_release_repository_full_name: ${{ github.event.inputs.repository_full_name }}
          rmk_release_version: ${{ github.event.inputs.version }}
          rmk_slack_channel: fhir-kodjin-cd
          rmk_slack_message_details: |
            GitHub Actions Build URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            GitHub Actions Build Number: ${{ github.run_number }}
          rmk_slack_notifications: true
          rmk_slack_webhook: ${{ secrets.RMK_SLACK_WEBHOOK }}
          rmk_update_skip_deploy: true
          rmk_version: ${{ github.event.inputs.rmk_version }}
